-- Create a table for public profiles using Supabase Auth
create table profiles (
  id uuid references auth.users not null,
  email text,
  username text unique,
  avatar_url text,
  mlbb_id text,
  rank text default 'Guerreiro III',
  balance decimal(10,2) default 0.00,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (id),
  constraint username_length check (char_length(username) >= 3)
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;

-- Create policies for profiles
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for matches
create table matches (
  id bigint generated by default as identity primary key,
  creator_id uuid references profiles(id) not null,
  opponent_id uuid references profiles(id),
  stake decimal(10,2) not null check (stake > 0),
  status text default 'ABERTO' check (status in ('ABERTO', 'EM_ANDAMENTO', 'FINALIZADO', 'CANCELADO')),
  winner_id uuid references profiles(id),
  proof_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for matches
alter table matches enable row level security;

-- Create policies for matches
create policy "Matches are viewable by everyone."
  on matches for select
  using ( true );

create policy "Authenticated users can create matches."
  on matches for insert
  with check ( auth.uid() = creator_id );

create policy "Players can update their matches."
  on matches for update
  using ( auth.uid() = creator_id or auth.uid() = opponent_id );

-- Create a table for transactions
create table transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  type text not null check (type in ('DEPOSITO', 'SAQUE', 'DUELO_WIN', 'DUELO_LOSS', 'DUELO_ENTRY')),
  amount decimal(10,2) not null,
  status text default 'PENDENTE' check (status in ('PENDENTE', 'CONFIRMADO', 'FALHA')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for transactions
alter table transactions enable row level security;

-- Create policies for transactions
create policy "Users can view their own transactions."
  on transactions for select
  using ( auth.uid() = user_id );

-- Function to handle new user signup automatically
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, username, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Setup Storage bucket for match proofs
insert into storage.buckets (id, name, public) 
values ('match-proofs', 'match-proofs', true)
on conflict (id) do nothing;

create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'match-proofs' );

create policy "Authenticated users can upload"
  on storage.objects for insert
  with check ( bucket_id = 'match-proofs' and auth.role() = 'authenticated' );
